version: '3.8'
services:
    dev-db:
        image: mysql
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: mysqlpassword
            MYSQL_USER: mysql
            MYSQL_DB: BMS
        volumes:
            - mysql-dev-data:/var/lib/mysql/data
    
    test-db:
        image: mysql
        ports:
            - 3308:3306
        environment:
            - MYSQL_USER=test
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DB=test
volumes:
     mysql-dev-data:
